### ISSUE TITLE
couple of suggestions

### ISSUE THREAD

**Issue by moham96** [LukeSmithxyz/dmenu#1]
Hi Luke,
I have a couple of suggestions to discuss
First it would be nice to have a "recency/frequency" sorting in dmenu, there are a lot of implementations for this out there, I currently use the manjaro implementation
https://gitlab.manjaro.org/packages/community/dmenu-manjaro
that uses the `dmenu_recency` script to achieve this but I wanted to know your opinion since I mostly use your scripts and builds.
Another great thing about the manjaro implementation is that it uses a dmenurc config file to pass the colors to dmenu, this doesn't require any patches to dmenu source code so you can pass the gruvbox colors and font modifications to vanilla dmenu, this means you don't need to keep updating the repo and users don't need to check it regularly for updates and instead just update the vanilla dmenu package from Ach repos.
Another cool implementation is https://github.com/kspi/dmenu-frecency

My other suggestion is a clipboard manager based on dmenu, there are many clipboard managers listed on the Arch wiki but a clipboard based on dmenu would be very nice to include in LARBS, my favorite implementation is: https://github.com/kspi/dmenu-frecency

Regards

**Comment by larsbergerproductions** [comment]
keep in mind this is the issues section, not a suggestion chat. If you have an issue, open up an issue here. One problem or idea should have its own issue for better referencing if issues are addressed within commits or pull requests. If you keep summing up multiple things into a single issue, those can't be addressed on their own and the issue can only be closed if every single point mentioned has been addressed. so KISS, pls.
