### ISSUE TITLE
I'd like to change the trasperency of "This Month" and "Appointments" so that it is completely opaque

### ISSUE THREAD

**Issue by wickedjargon** [LukeSmithxyz/dmenu#11]
I'd like to change the trasperency of "This Month" and "Appointments" so that it is completely opaque, instead of semi-transparent:

![](https://imgur.com/QAc1eKfl.png)

**Comment by Lin2Jing4** [comment]
In [.local/bin/statusbar/sb-clock](https://github.com/LukeSmithxyz/voidrice/blob/4231d6bd33d484624293662dd6c40c768dc89875/.local/bin/statusbar/sb-clock#L22), to [suspend](https://man.archlinux.org/man/killall.1) the [xcompmgr](https://wiki.archlinux.org/title/xcompmgr#Tips_and_tricks) process and resume it later, replace
```sh
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
```
with
```sh
        1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" && killall xcompmgr && sleep 5 && (xcompmgr & ) ;;
```
. Or, to [remove](https://wiki.archlinux.org/title/pacman#Removing_packages) the [xcompmgr](https://archlinux.org/packages/extra/x86_64/xcompmgr/) package, try `pacman -R xcompmgr`.

**Comment by wickedjargon** [comment]
Replacing the code in  `.local/bin/statusbar/sb-clock` as suggested above didn't work, but updating `.config/x11/xprofile` to remove `xcompmgr &`  resolved the issue. Thanks for pointing me in the right direction @Lin2Jing4
