### ISSUE TITLE
Why dmenu_run shows no programs at all

### ISSUE THREAD

**Issue by pineapples5972** [LukeSmithxyz/dmenu#13]
![image](https://user-images.githubusercontent.com/62638787/170550952-479399fb-57d9-4379-bf4e-4dc1379ed241.png)
dmenu_run supposed to show installed programs from the path.
I have $PATH set up correctly and all and before i upgraded to this build of dmenu my dmenu_run were working correctly.

So is this intentionally like this or its a bug?

**Comment by LukeSmithxyz** [comment]
Your cache file has probably been blanked or is unreadable.

`rm ~/.cache/dmenu_run`.

**Comment by pineapples5972** [comment]
> Your cache file has probably been blanked or is unreadable.
> 
> `rm ~/.cache/dmenu_run`.

Ohh Thanks. Removing It worked. Learned New thing today. 😇
