### ISSUE TITLE
colors implementation

### ISSUE THREAD

**Issue by 1edenec** [LukeSmithxyz/dmenu#2]
Hi, Luke. I found some issue with this fork. 
First of all - I have some theme implementation in ~/.Xresources.
If i don't use my theme, implemented with ~/.Xresources, everything working good, but when it is, i can't change some colors at the dmenu.
for example: 
dmenu_run -i -nb '#fdf6e3' -nf '#586c75' -sf '#fdf6e3' -sb '#b58900'
only one color implemented with -nb works, other colors don't work.

**Comment by ToppDev** [comment]
This is related to the xresources patch. A quick and dirty fix is, to reread the command line arguments again after the `read_Xresources();` function call in the `main()` function.

e.g.
```C++
read_Xresources();

for (i = 1; i < argc; i++)
	if (!strcmp(argv[i], "-fn"))  /* font or font set */
		fonts[0] = argv[++i];
	else if (!strcmp(argv[i], "-nb"))  /* normal background color */
		colors[SchemeNorm][ColBg] = argv[++i];
	else if (!strcmp(argv[i], "-nf"))  /* normal foreground color */
		colors[SchemeNorm][ColFg] = argv[++i];
	else if (!strcmp(argv[i], "-sb"))  /* selected background color */
		colors[SchemeSel][ColBg] = argv[++i];
	else if (!strcmp(argv[i], "-sf"))  /* selected foreground color */
		colors[SchemeSel][ColFg] = argv[++i];
```
