### ISSUE TITLE
Passwords are visible (all of a sudden)

### ISSUE THREAD

**Issue by nerrufam** [LukeSmithxyz/dmenu#3]
i know that it didn't used to show passwords, probably must update a config.
What i've tried:
in ~/.local/bin/dmenupass , i left only " dmenu -p "$1" <&- " without "&& echo".
since that didnt work, i tried to make the every color black, so it would write black text on black background, 😅 didnt work either, dmenu would be to intelligent to change the font color.

( to test this i would only run "sudo st" )

**Comment by LukeSmithxyz** [comment]
Ah I'm going to guess this is due to the addition of the transparency patch and such. I'll try to figure it out when I can.

**Comment by LukeSmithxyz** [comment]
fixed in 2d9878f5babb86ad2d41f7926613dcaa8413d36f
