### ISSUE TITLE
Errors in Error in /usr/share/mutt-wizard/mutt-wizard.muttrc - no such function

### ISSUE THREAD

**Issue by xavierbaez** [LukeSmithxyz/dmenu#9]
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 53: view-raw-message: no such function in map
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 55: top-page: no such function in map
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 56: bottom-page: no such function in map
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 94: index_author: no such object
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 95: index_number: no such object
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 96: index_subject: no such object
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 100: index_author: no such object
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 101: index_subject: no such object
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 105: index_author: no such object
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 106: index_subject: no such object
Error in /home/xavier/.config/mutt/muttrc, line 2: source: errors in /usr/share/mutt-wizard/mutt-wizard.muttrc
source: errors in /home/xavier/.config/mutt/muttrc

**Comment by LukeSmithxyz** [comment]
Install neomutt.
